"""feat: add advanced claim and doc fields

Revision ID: 09016fb8a25a
Revises: f76daebbb1b8
Create Date: 2025-06-17 11:20:26.340073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09016fb8a25a'
down_revision: Union[str, None] = 'f76daebbb1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('eligibility_status', sa.String(length=50), nullable=True))
    op.add_column('claims', sa.Column('assigned_cpt_codes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('claims', sa.Column('assigned_icd10_codes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('claims', sa.Column('compliance_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('patient_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('document_purpose', sa.String(length=50), nullable=True))
    op.alter_column('documents', 'claim_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'documents', 'patients', ['patient_id'], ['id'])
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'claim_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('documents', 'document_purpose')
    op.drop_column('documents', 'patient_id')
    op.drop_column('claims', 'compliance_flags')
    op.drop_column('claims', 'assigned_icd10_codes')
    op.drop_column('claims', 'assigned_cpt_codes')
    op.drop_column('claims', 'eligibility_status')
    # ### end Alembic commands ###
