"""rename raw_text to parsed_text on documents

Revision ID: 203e2668be08
Revises: 4d2a39e4e8aa
Create Date: 2025-06-18 18:34:21.101624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203e2668be08'
down_revision: Union[str, None] = '4d2a39e4e8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_text', sa.Text(), nullable=True))
    op.drop_column('documents', 'raw_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'parsed_text')
    # ### end Alembic commands ###
