"""add cascade delete for policy benefits

Revision ID: 2be22f49ef12
Revises: ce87a7a6058e
Create Date: 2025-06-18 19:57:04.859944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be22f49ef12'
down_revision: Union[str, None] = 'ce87a7a6058e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('policy_benefits_patient_id_fkey'), 'policy_benefits', type_='foreignkey')
    op.create_foreign_key(None, 'policy_benefits', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policy_benefits', type_='foreignkey')
    op.create_foreign_key(op.f('policy_benefits_patient_id_fkey'), 'policy_benefits', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
