"""add patient address sex and relationship to claims

Revision ID: 468bc504f4cd
Revises: b9d287418ff4
Create Date: 2025-06-19 19:21:26.397922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468bc504f4cd'
down_revision: Union[str, None] = 'b9d287418ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('patient_sex', sa.String(length=10), nullable=True))
    op.add_column('claims', sa.Column('patient_address', sa.Text(), nullable=True))
    op.add_column('claims', sa.Column('patient_relationship_to_insured', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'patient_relationship_to_insured')
    op.drop_column('claims', 'patient_address')
    op.drop_column('claims', 'patient_sex')
    # ### end Alembic commands ###
