"""add vector column to meriplex docs

Revision ID: 5e6551a52124
Revises: 59e4a0640bef
Create Date: 2025-08-13 15:50:42.607145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '5e6551a52124'
down_revision: Union[str, None] = '59e4a0640bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meriplex_documents', sa.Column('vector', pgvector.sqlalchemy.Vector(dim=3072), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meriplex_documents', 'vector')
    # ### end Alembic commands ###
