"""feat: add comprehensive rcm models

Revision ID: 6a160edef1bb
Revises: 09016fb8a25a
Create Date: 2025-06-17 19:30:25.773435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a160edef1bb'
down_revision: Union[str, None] = '09016fb8a25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_value', sa.String(length=50), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_value', 'code_type', name='_code_value_type_uc')
    )
    op.create_index(op.f('ix_medical_codes_code_type'), 'medical_codes', ['code_type'], unique=False)
    op.create_index(op.f('ix_medical_codes_code_value'), 'medical_codes', ['code_value'], unique=False)
    op.create_table('policy_benefits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('benefit_type', sa.String(length=255), nullable=False),
    sa.Column('cpt_code_match', sa.String(length=50), nullable=True),
    sa.Column('is_covered', sa.Boolean(), nullable=True),
    sa.Column('coverage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('co_pay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deductible', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_benefits_patient_id'), 'policy_benefits', ['patient_id'], unique=False)
    op.add_column('claims', sa.Column('submission_date', sa.DateTime(), nullable=True))
    op.add_column('claims', sa.Column('adjudication_date', sa.DateTime(), nullable=True))
    op.add_column('claims', sa.Column('patient_responsibility_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('claims', sa.Column('payer_paid_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('claims', sa.Column('edi_transaction_id', sa.String(length=255), nullable=True))
    op.alter_column('claims', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('claims', 'assigned_cpt_codes')
    op.drop_column('claims', 'assigned_icd10_codes')
    op.add_column('service_lines', sa.Column('code_confidence_score', sa.Numeric(precision=5, scale=4), nullable=True))
    op.drop_column('service_lines', 'confidence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_lines', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.drop_column('service_lines', 'code_confidence_score')
    op.add_column('claims', sa.Column('assigned_icd10_codes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('assigned_cpt_codes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.alter_column('claims', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('claims', 'edi_transaction_id')
    op.drop_column('claims', 'payer_paid_amount')
    op.drop_column('claims', 'patient_responsibility_amount')
    op.drop_column('claims', 'adjudication_date')
    op.drop_column('claims', 'submission_date')
    op.drop_index(op.f('ix_policy_benefits_patient_id'), table_name='policy_benefits')
    op.drop_table('policy_benefits')
    op.drop_index(op.f('ix_medical_codes_code_value'), table_name='medical_codes')
    op.drop_index(op.f('ix_medical_codes_code_type'), table_name='medical_codes')
    op.drop_table('medical_codes')
    # ### end Alembic commands ###
