"""add vector column to medical codes

Revision ID: 7b04974c33ec
Revises: 6a160edef1bb
Create Date: 2025-06-18 09:39:08.501642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7b04974c33ec'
down_revision: Union[str, None] = '6a160edef1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_codes', sa.Column('vector', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    op.add_column('service_lines', sa.Column('diagnosis_pointer', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_lines', 'diagnosis_pointer')
    op.drop_column('medical_codes', 'vector')
    # ### end Alembic commands ###
