"""add ondelete cascade for service lines

Revision ID: b9d287418ff4
Revises: 2be22f49ef12
Create Date: 2025-06-18 20:22:34.377145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d287418ff4'
down_revision: Union[str, None] = '2be22f49ef12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('service_lines_claim_id_fkey'), 'service_lines', type_='foreignkey')
    op.create_foreign_key(None, 'service_lines', 'claims', ['claim_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_lines', type_='foreignkey')
    op.create_foreign_key(op.f('service_lines_claim_id_fkey'), 'service_lines', 'claims', ['claim_id'], ['id'])
    # ### end Alembic commands ###
