"""add ondelete cascade to patient relationships

Revision ID: ce87a7a6058e
Revises: 203e2668be08
Create Date: 2025-06-18 19:54:32.700129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce87a7a6058e'
down_revision: Union[str, None] = '203e2668be08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('claims_patient_id_fkey'), 'claims', type_='foreignkey')
    op.create_foreign_key(None, 'claims', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_patient_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_patient_id_fkey'), 'documents', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.create_foreign_key(op.f('claims_patient_id_fkey'), 'claims', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
