"""add diagnosis pointer to service lines

Revision ID: fe172d3f4048
Revises: 6a160edef1bb
Create Date: 2025-06-17 23:56:15.595572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe172d3f4048'
down_revision: Union[str, None] = '6a160edef1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_lines', sa.Column('diagnosis_pointer', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_lines', 'diagnosis_pointer')
    # ### end Alembic commands ###
